### ISSUE TITLE
not enough arguments error during go get

### ISSUE THREAD

**Issue by jbayer** [pivotal-cf-experimental/veritas#4]
$ go get -u github.com/pivotal-cf-experimental/veritas
# github.com/pivotal-cf-experimental/veritas/lrps/remove_lrp
../../go/src/github.com/pivotal-cf-experimental/veritas/lrps/remove_lrp/remove_lrp.go:21: not enough arguments in call to store.RemoveDesiredLRPByProcessGuid
# github.com/pivotal-cf-experimental/veritas/store/fetch_store
../../go/src/github.com/pivotal-cf-experimental/veritas/store/fetch_store/fetch_store.go:44: not enough arguments in call to store.Tasks
# github.com/pivotal-cf-experimental/veritas/lrps/submit_lrp
../../go/src/github.com/pivotal-cf-experimental/veritas/lrps/submit_lrp/submit_lrp.go:60: not enough arguments in call to store.DesireLRP

**Comment by onsi** [comment]
fixed now :)
